name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: install node_modules
      run: npm install

    - name: install latest @rbxts/types for tests
      run: |
        pushd tests >/dev/null
        npm install @rbxts/types
        popd >/dev/null

    - name: install lua
      uses: leafo/gh-actions-lua@v2
      with:
        luaVersion: "5.2.4"

    - name: install luarocks
      uses: leafo/gh-actions-luarocks@v2

    - name: install luarocks packages
      run: |
        luarocks install luafilesystem
        luarocks install dkjson
        luarocks install bit32

    - name: tslint
      run: npm run tslint

    - name: prettylint
      run: npm run prettylint

    - name: test
      run: npm run ci

    - name: coverage
      run: npm run coverage

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - run: |
          git checkout master tests/package.json
          git checkout master tests/package-lock.json
          npm version prerelease --preid="commit-$(git log --format="%H" -n 1 | head -c 7)" # hack!
