name: CI

on:
  pull_request_target:
  push:
    branches:
      - master

jobs:
  build-and-lint:
    if: contains(github.event.commits[0].message, '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install NPM dependencies and compile
        uses: bahmutov/npm-install@v1.1.0

      - name: Run ESLint
        run: npm run eslint
  unit-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install NPM dependencies and compile
        uses: bahmutov/npm-install@v1.1.0

      - name: Verify ROBLOSECURITY
        run: |
          If([string]::IsNullOrEmpty("${{ secrets.ROBLOSECURITY }}")) {
            echo "ROBLOSECURITY secret has not been set! Please refer to CONTRIBUTING.md";
            exit 1;
          }

      - name: Install Python dependencies
        run: pip install wget psutil

      - name: Install Roblox Studio
        run: python tests/scripts/install.py "${{ secrets.ROBLOSECURITY }}"

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rojo and run-in-roblox
        run: foreman install

      - name: Compile and run tests
        run: npm test

      - name: Report Coverage
        continue-on-error: true
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
