name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-lint:
    if: contains(github.event.commits[0].message, '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Install NPM dependencies and compile
        uses: bahmutov/npm-install@v1.4.5

      - name: Run ESLint
        run: npm run eslint
  unit-tests:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Install NPM dependencies and compile
        uses: bahmutov/npm-install@v1.4.5

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY || '_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_74522B15E276B85DD70BCCCB10066A8F46647924B7EB3B3A012A1FD823E97528A21B496E581B19D31B390EB12289105009DF99120603EF292C61676122B4CC4AF2B64F395E82308866D308D6B868834F01CC5C87BB764FC5A736FD5DABAFA571DD665D2E249A62D341AF879F165A398BD3BA88227EA2EA755394AD1FD306814DDA7810065398206CAF39AA8EB5F2F0AE5E4CDD1000B83A5F7AEC592E53B7A93476201DB17DD596BB1E0030B72F630BB2E526A7F2AEDD31FF6B7F15648A09B8F604BE9E25C899BF52D78B3378465BB032F318CF332BFE6E40936B84A26EB5E5B38DE053B13A30D4FBFF0C09AE02D0DFCA388A3FE238A5377318D5E06DC0FFAAD54C8436C2509A228F982257347266F2AF0677820DAE2E99FEBFEEEB26431E677D3D6CF8E6' }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile and run tests
        run: npm test

      - name: Report Coverage
        continue-on-error: true
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
