name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0

    - name: Install NodeJS
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: Install Node_modules
      run: npm install

    - name: Install Latest @rbxts/types for tests
      run: |
        pushd tests >/dev/null
        npm install @rbxts/types@latest
        popd >/dev/null

    - name: Install Lua
      uses: leafo/gh-actions-lua@master
      with:
        luaVersion: 5.1

    - name: Install Luarocks
      uses: leafo/gh-actions-luarocks@master

    - name: Install Luarocks Packages
      run: |
        luarocks install luafilesystem
        luarocks install dkjson
        luarocks install bit32

    - name: Run TSLint
      run: npm run tslint

    - name: Run PrettyLint
      run: npm run prettylint

    - name: Run Tests
      run: npm run ci

    - name: Generate Coverage
      run: npm run coverage

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}

    - run: echo "${{ github.ref }}"

  deploy:
    if: github.ref == 'master'
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@master
    - name: Deploy
      run: echo "${{ github.ref }}"
      # run: |
      #   git config user.name "GitHub Actions"
      #   git config user.email "noreply@github.com"
      #   git fetch
      #   git checkout origin/master tests/package.json
      #   git checkout origin/master tests/package-lock.json
      #   npm version "commit-$(git log --format="%H" -n 1 | head -c 7)" # hack!
