name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0

    - name: Install Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install Node_modules
      run: npm install

    - name: Install Latest @rbxts/types for tests
      run: |
        pushd tests >/dev/null
        npm install @rbxts/types
        popd >/dev/null

    - name: Install Lua
      uses: leafo/gh-actions-lua@master
      with:
        luaVersion: 5.1

    - name: Install Luarocks
      uses: leafo/gh-actions-luarocks@master

    - name: Install Luarocks Packages
      run: |
        luarocks install luafilesystem
        luarocks install dkjson
        luarocks install bit32

    - name: Run TSLint
      run: npm run tslint

    - name: Run PrettyLint
      run: npm run prettylint

    - name: Run Tests
      run: npm run ci

    - name: Generate Coverage
      run: npm run coverage

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GH_TOKEN }}

    - name: Deploy
      run: |
        git checkout master tests/package.json
        git checkout master tests/package-lock.json
        npm version prerelease --preid="commit-$(git log --format="%H" -n 1 | head -c 7)" # hack!
