name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0

    - run: sudo apt-get install tree
    - run: tree

    - name: install nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: install node_modules
      run: npm install

    - name: install latest @rbxts/types for tests
      run: |
        pushd tests >/dev/null
        npm install @rbxts/types
        popd >/dev/null

    - name: install lua
      uses: leafo/gh-actions-lua@v2
      with:
        luaVersion: "5.1.5"

    - name: install luarocks
      uses: leafo/gh-actions-luarocks@v2

    - name: install luarocks packages
      run: |
        luarocks install luafilesystem
        luarocks install dkjson

    - name: tslint
      run: npm run tslint

    - name: prettylint
      run: npm run prettylint

    - name: test
      run: npm run ci

    - name: coverage
      run: npm run coverage

    - run: |
        git checkout master tests/package.json
        git checkout master tests/package-lock.json
        npm version prerelease --preid="commit-$(git log --format="%H" -n 1 | head -c 7)" # hack!
