name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Install NodeJS
      uses: actions/setup-node@master
      with:
        node-version: 10.x
        registry-url: 'https://registry.npmjs.org'

    - name: Install Node_modules
      run: npm install

    - name: Install Latest @rbxts/types for tests
      run: |
        pushd tests >/dev/null
        npm install @rbxts/types@latest
        popd >/dev/null

    - name: Install Lua
      uses: leafo/gh-actions-lua@master
      with:
        luaVersion: 5.1

    - name: Install Luarocks
      uses: leafo/gh-actions-luarocks@master

    - name: Install Luarocks Packages
      run: |
        luarocks install luafilesystem
        luarocks install dkjson
        luarocks install bit32

    - name: Run TSLint
      run: npm run tslint

    - name: Run PrettyLint
      run: npm run prettylint

    - name: Run Tests
      run: npm run ci

    - name: Generate Coverage
      run: npm run coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}

    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "noreply@github.com"
        git checkout origin/master tests/package.json
        git checkout origin/master tests/package-lock.json
        npm version prerelease --preid="commit-$(git log --format="%H" -n 1 | head -c 7)" # hack!
        npm publish --tag next
      env:
        NODE_AUTH_TOKEN: ${{ secrets.npm_token }}